name: Manual Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: choice
        required: true
        default: fix
        options:
          - fix
          - feat
      dryRun:
        description: 'DryRun'
        type: boolean
        default: true
# ENV and Config
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
  GIT_AUTHOR_NAME: github-actions
  GIT_AUTHOR_EMAIL: github-actions@github.com
  GIT_COMMITTER_NAME: github-actions
  GIT_COMMITTER_EMAIL: github-actions@github.com
  CI: true
  CONFIG_PYTHON_VERSION: '["3.x"]'
  CONFIG_OS: '["ubuntu-latest"]'
# Main Job
jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      PYTHON_VERSION: ${{ steps.set-config.outputs.CONFIG_PYTHON_VERSION }}
      OS: ${{ steps.set-config.outputs.CONFIG_OS }}
      DRY_RUN: ${{ github.event.inputs.dryRun == 'true' }}
    steps:
      - id: set-config
        run: |
          echo "CONFIG_PYTHON_VERSION=${{ toJSON(env.CONFIG_PYTHON_VERSION) }}" >> $GITHUB_OUTPUT
          echo "CONFIG_OS=${{ toJSON(env.CONFIG_OS) }}" >> $GITHUB_OUTPUT
          if [[ github.event.inputs.dryRun == 'true' ]]; then
               echo "DRY_RUN=--noop" >> "$GITHUB_ENV"
          else
              echo "DRY_RUN=''" >> "$GITHUB_ENV"
          fi
  release-manual:
    name: Test, Build and force Release
    needs: config

    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ${{ fromJSON(needs.config.outputs.OS) }}
        PYTHON_VERSION: ${{ fromJSON(needs.config.outputs.PYTHON_VERSION) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
      - name: Commit trigger
        run: |
          git commit --allow-empty -m "${{ github.event.inputs.version }}: Trigger Manual Release"
      - name: Create a release - ${{ github.event.inputs.version }}
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_API_TOKEN }}
          additional_options: env.DRY_RUN

  deploy:
    needs: [config, release-manual]
    name: Build and publish Python 🐍 distributions 📦 to TestPyPI
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ${{ fromJSON(needs.config.outputs.OS) }}
        PYTHON_VERSION: ${{ fromJSON(needs.config.outputs.PYTHON_VERSION) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
      - name: Install pypa/build
        run: |
          python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
