name: Manual Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: choice
        required: true
        default: fix
        options:
          - fix
          - feat
          - major
      dryRun:
        description: 'DryRun'
        type: boolean
        default: true
# ENV and Config
env:
  GIT_AUTHOR_NAME: github-actions
  GIT_AUTHOR_EMAIL: github-actions@github.com
  GIT_COMMITTER_NAME: github-actions
  GIT_COMMITTER_EMAIL: github-actions@github.com
  CI: true
  CONFIG_PYTHON_VERSION: '["3.x"]'
  CONFIG_OS: '["ubuntu-latest"]'
  COMMIT_MESSAGE_ENV: "Trigger Manual Release"
  COMMIT_MESSAGE_MAJOR_ENV: "BREAKING CHANGE: Forced Major update without changes"

# Main Job
jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      PYTHON_VERSION: ${{ steps.set-config.outputs.CONFIG_PYTHON_VERSION }}
      OS: ${{ steps.set-config.outputs.CONFIG_OS }}
    steps:
      - id: set-config
        run: |
          echo "CONFIG_PYTHON_VERSION=${{ toJSON(env.CONFIG_PYTHON_VERSION) }}" >> $GITHUB_OUTPUT
          echo "CONFIG_OS=${{ toJSON(env.CONFIG_OS) }}" >> $GITHUB_OUTPUT
  release-manual:
    name: Test, Build and force Release
    needs: config

    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ${{ fromJSON(needs.config.outputs.OS) }}
        PYTHON_VERSION: ${{ fromJSON(needs.config.outputs.PYTHON_VERSION) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
#      - name: Fetch tags
#        run: git fetch --tags
      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
      - name: Commit trigger
        run: >
          export COMMIT_MESSAGE_PREFIX="${{ github.event.inputs.version == 'major' && 'ci' || github.event.inputs.version }}" &&
          export COMMIT_MESSAGE="$COMMIT_MESSAGE_PREFIX: ${{ env.COMMIT_MESSAGE_ENV }}" &&
          export COMMIT_MESSAGE_MAJOR="${{ github.event.inputs.version == 'major' && env.COMMIT_MESSAGE_MAJOR_ENV || '' }}" &&
          git commit --allow-empty 
          -m "$COMMIT_MESSAGE"
          -m "$COMMIT_MESSAGE_MAJOR"
      - name: Create a release - ${{ github.event.inputs.version }}
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_API_TOKEN }}
          additional_options: "${{ github.event.inputs.dryRun == 'true' && '--noop' || '' }}"

  deploy:
    needs: [config, release-manual]
    name: Build and publish Python 🐍 distributions 📦 to TestPyPI
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ${{ fromJSON(needs.config.outputs.OS) }}
        PYTHON_VERSION: ${{ fromJSON(needs.config.outputs.PYTHON_VERSION) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
      - name: Install pypa/build
        run: |
          python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
